spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/socialmanager?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: 123456
  servlet:
    multipart:
      max-file-size: 300000
      max-request-size: 300000


mybatis:
  type-aliases-package: com.jd.socialmanager.entity
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    com.jd.socialmanager.dao: debug
